gui:
  nerdFontsVersion: "3"

# Theme
theme:
  background: "#282828"
  foreground: "#ebdbb2"
  cursor: "#c7c7c7"
  black: "#1d2021"
  red: "#cc241d"
  green: "#98871a"
  yellow: "#d79921"
  blue: "#458588"
  magenta: "#b16286"
  cyan: "#689d6a"
  white: "#c7c7c7"
  brightBlack: "#676767"
  brightRed: "#fb4934"
  brightGreen: "#b8bb26"
  brightYellow: "#fabd2f"
  brightBlue: "#83a598"
  brightMagenta: "#d3869b"
  brightCyan: "#8ec07c"
  brightWhite: "#f9f5d7"


  # theme:
  #   activeBorderColor:
  #     - "#fabd2f"  # Gruvbox yellow
  #     - bold
  #   inactiveBorderColor:
  #     - "#a89984"  # Gruvbox gray
  #   optionsTextColor:
  #     - "#b8bb26"  # Gruvbox green
  #   selectedLineBgColor:
  #     - "#3c3836"  # Gruvbox dark gray
  #   selectedRangeBgColor:
  #     - "#504945"  # Gruvbox medium gray
  #   cherryPickedCommitBgColor:
  #     - "#8ec07c"  # Gruvbox light blue
  #   cherryPickedCommitFgColor:
  #     - "#282828"  # Gruvbox background
  #   unstagedChangesColor:
  #     - "#fb4934"  # Gruvbox red
  #   defaultFgColor:
  #     - "#ebdbb2"  # Gruvbox foreground
  #   searchingActiveBorderColor:
  #     - "#1d2021"  # Gruvbox orange
  #   cmdFgColor:
  #     - "#ebdbb2"  # Gruvbox foreground
  #   mainPanelBorderColor:
  #     - "#a89984"  # Gruvbox gray
  #   mainPanelShadowColor:
  #     - "#282828"  # Gruvbox background