gui:
  nerdFontsVersion: "3"

# Theme
theme:
  background: "#fc4384"
  foreground: "#dddad6"
  cursor: "#c7c7c7"
  black: "#7a7a7a"
  red: "#fc4384"
  green: "#b3e33b"
  yellow: "#ffa727"
  blue: "#102895"
  magenta: "#c930c7"
  cyan: "#00c5c7"
  white: "#c7c7c7"
  brightBlack: "#676767"
  brightRed: "#ff7fac"
  brightGreen: "#c8ed71"
  brightYellow: "#ebdf86"
  brightBlue: "#6871ff"
  brightMagenta: "#ff76ff"
  brightCyan: "#5ffdff"
  brightWhite: "#fffefe"