#! /bin/sh

bspc monitor DP-1 -d  I II III IV V VI VII VIII IX X
#bspc monitor LVDS-1 -d  I II III IV V VI VII VIII
#bspc monitor HDMI-1 IX X
sxhkd &

#nm-applet &disown

#picom &
#dunst &
#blueman-applet & disown

#KDE Plasma Panel 

#bspc config bottom_padding 15

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding		15

bspc config split_ratio          0.66
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#353535'
#gruvbox orange
bspc config focused_border_color "#ebdbb2"

bspc config presel_border_color "#9a875f"

bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
bspc rule -a Picture-in-Picture state=floating
#bspc rule -a Blueman-manager='^10'
#bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh

feh --bg fill /home/ks/Pictures/bg.png
nitrogen --restore &
flameshot &disown
mpd &disown
setxkbmap de us
#xmodmap -e "keycode 108 = Alt_L"
