#!/bin/bash

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
sudo dnf install cmake gcc-c++ make python3-devel golang mono-core npm nodejs java
python3 $HOME/.vim/bundle/youcompleteme/install.py --all 
